CREATE TABLE `im1` (
  `id` int(11) NOT NULL,
  `recipent` int(11) DEFAULT NULL,
  `im` text,
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

ALTER TABLE `im1` ADD PRIMARY KEY (`id`);
